name: sast

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sast:
    uses: opensourceways/agent-development-specification/.github/workflows/sast-reusable.yml@main
    with:
      runs-on: ubuntu-latest
